config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :data_packs, only: [:index, :show], path: '/data-packs'
  resources :card_types, only: [:show], path: '/card-types'
  resources :cards, only: [:index, :show]
  get "/decks/new/corporation", to: 'decks#new', faction: "Corporation"
  get "/decks/new/runner", to: 'decks#new', faction: "Runner"
  get "/decks/:id", to: 'decks#edit'
  resources :decks, except: [:edit]

  root 'pages#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :faction
  belongs_to :identity
  belongs_to :data_pack
  has_many :decks, through: :deck_cards
  has_many :deck_cards
  has_and_belongs_to_many :card_types

  extend FriendlyId
  friendly_id :name, use: :slugged

  def card_image
    image_id.present? ? "cards/#{image_id}.png" : "cards/blank.png"
  end

  def agenda?
    card_types.collect(&:name).include?("Agenda")
  end

  def formatted_description
    text = description.gsub("[Click]", "<span class='icon icon-click'></span>")
    text = text.gsub("[Subroutine]", "<span class='icon icon-subroutine'></span>")
    text = text.gsub("[Credits]", "<span class='icon icon-credit'></span>")
    text = text.gsub("[Memory Unit]", "<span class='icon icon-mu'></span>")
    text = text.gsub("[Recurring Credits]", "<span class='icon icon-recurring-credit'></span>")
    text = text.gsub("[Link]", "<span class='icon icon-link'></span>")
    text.html_safe
  end
end

app/models/card_type.rb
class CardType < ActiveRecord::Base
  has_and_belongs_to_many :cards

  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.identity
    where(name: ["Neutral", "Anarch", "Criminal", "Shaper", "Haas-Bioroid", "Jinteki", "Weyland Consortium", "NBN"])
  end

  def self.not_identity
    where.not(name: ["Neutral", "Anarch", "Criminal", "Shaper", "Haas-Bioroid", "Jinteki", "Weyland Consortium", "NBN"])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all.sort_by &:created_at
  end

  def show
    @card = Card.friendly.find(params[:id])
  end
end

app/views/cards/index.html.erb
<%= cache ['cards#index', 'v1'], :expires_in => 1.hour do %>
  <% content_for :title, "Cards" %>
  <div class="row">
    <% @cards.each do |card| %>
      <div class="card col-xs-4 col-md-3">
        <%= link_to image_tag(card.card_image), card_path(card) %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/cards/show.html.erb
<%= cache ['cards#show', @card, 'v1'], :expires_in => 1.hour do %>
  <% content_for :title, @card.name %>
  <div class="card row">
    <div class="col-xs-3">
      <%= image_tag @card.card_image %>
    </div>

    <div class="col-xs-9 ">
      <h2>
        <%= @card.name %>
      </h2>

      <h3>
        <% @card.card_types.each do |type| %>
          <%= link_to type.name, card_type_path(type) %>
        <% end %>
      </h3>

      <dl>
        <% if @card.cost %>
          <dt>Cost</dt>
          <dd><%= @card.cost %></dd>
        <% end %>

        <% if @card.max_influence %>
          <dt>Max Influence</dt>
          <dd><%= @card.max_influence %></dd>
        <% end %>

        <% if @card.deck_minimum_cards %>
          <dt>Deck Minimum Cards</dt>
          <dd><%= @card.deck_minimum_cards %></dd>
        <% end %>

        <% if @card.influence %>
          <dt>Influence</dt>
          <dd><%= @card.influence %></dd>
        <% end %>

        <% if @card.strength %>
          <dt>Strength</dt>
          <dd><%= @card.strength %></dd>
        <% end %>

        <% if @card.memory_units %>
          <dt>Memory Unit(s)</dt>
          <dd><%= @card.memory_units %></dd>
        <% end %>

        <% if @card.advancement_cost %>
          <dt>Advancement Cost</dt>
          <dd><%= @card.advancement_cost %></dd>
        <% end %>

        <% if @card.agenda_point %>
          <dt>Agenda Points</dt>
          <dd><%= @card.agenda_point %></dd>
        <% end %>

        <% if @card.trash_cost %>
          <dt>Trash Cost</dt>
          <dd><%= @card.trash_cost %></dd>
        <% end %>

        <% if @card.link %>
          <dt>Link</dt>
          <dd><%= @card.link %></dd>
        <% end %>
      </dl>

      <p><%= @card.formatted_description %></p>
    </div>
  </div>
<% end %>