config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :data_packs, only: [:index, :show], path: '/data-packs'
  resources :card_types, only: [:show], path: '/card-types'
  resources :cards, only: [:index, :show]
  get "/decks/new/corporation", to: 'decks#new', faction: "Corporation"
  get "/decks/new/runner", to: 'decks#new', faction: "Runner"
  get "/decks/:id", to: 'decks#edit'
  resources :decks, except: [:edit]

  root 'pages#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :faction
  belongs_to :user

  has_many :cards, through: :deck_cards
  has_many :deck_cards, dependent: :destroy
  accepts_nested_attributes_for :deck_cards, reject_if: :all_blank, allow_destroy: true

  validates :identity_card_id, presence: true

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate_user!

  def index
    @decks = current_user.decks
  end

  def new
    @faction = Faction.find_by_name!(params["faction"])
    @deck = Deck.new(faction: @faction)
    gather_form_requirements
    @deck.deck_cards.build
  end

  def edit
    @deck = Deck.find(params[:id])
    redirect_to root_path if @deck.user != current_user
    @faction = @deck.faction
    gather_form_requirements
    @deck.deck_cards.build
  end

  def create
    @deck = Deck.new(deck_params)

    if @deck.save!
      @deck.deck_cards.create
      @deck.deck_cards.where(number: nil).destroy_all
      redirect_to decks_path
    end
  end

  def update
    @deck = Deck.find(params[:id])
    redirect_to root_path if @deck.user != current_user
    @deck.deck_cards.destroy_all
    if @deck.update_attributes!(deck_params)
      @deck.deck_cards.where(number: nil).destroy_all
      redirect_to decks_path
    end
  end

  private

  def gather_form_requirements
    @identities = @faction.cards.select{|c| c.card_types.collect(&:name).include? "Identity"}
    @cards = sort_and_group_cards Card.where(faction: @faction).preload(:card_types)

  end

  def deck_params
    params.require(:deck).permit(:name, :identity_card_id, :deck, :id, :user, :user_id, :faction_id, deck_cards_attributes: [:card_id, :deck_id, :number, :_destroy])
  end

  def sort_and_group_cards(faction_cards)
    cards = {}
    faction_cards.each do |card|
      ["Agenda", "Asset", "ICE", "Operation", "Upgrade", "Event", "Hardware", "Program", "Resource"].each do |card_type|
        if card.card_types.collect(&:name).include? card_type
          if cards[card_type.downcase.to_sym].present?
            cards[card_type.downcase.to_sym] << card
          else
            cards[card_type.downcase.to_sym] = [card]
          end
        end
      end
    end

    cards
  end
end

app/views/decks/_deck_card.html.erb
<tr data-identity-slug="<%= card.identity.slug %>" class="deck-card <%= card.card_types.collect(&:slug).join(' ') %>">
  <td class="number">
    <%= hidden_field_tag "deck[deck_cards_attributes][#{count}][number]", @deck.deck_cards.where(card_id: card.id).try(&:first).try(&:number), class: "number-field" %>
    <%= hidden_field_tag "deck[deck_cards_attributes][#{count}][card_id]", card.id  %>
  </td>
  <td class="name">
    <span class="card-description" data-toggle="popover" title="<%= card.name %>" data-agenda="<%= card.agenda_point %>" data-content="<img src='<%= image_url card.card_image %>'>"><%= card.name %></span>
  </td>
  <td class="identity">
    <i data-toggle="tooltip" title="<%= card.identity.name %>" class="icon icon-<%= card.identity.slug %>"></i>
  </td>
  <td class="card-types">
    <% card.card_types.not_identity.each do |type| %>
      <i data-toggle="tooltip" title="<%= type.name %>" class="icon icon-<%= type.slug %>"></i>
    <% end %>
  </td>
  <td class="influence"><%= card.influence %></td>
</tr>

app/views/decks/_form.html.erb
<%= simple_form_for @deck do |f| %>
  <div class="row">
    <%= f.input :faction_id, as: :hidden, input_html: { value: @faction.id } %>
    <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>

    <div data-faction="<%= @deck.faction.name.downcase %>" class="identity col-md-5"%>
      <div class="panel panel-default">
        <div class="panel-heading"><%= f.input :name %></div>
        <div class="panel-body selected-identity">
          <%= f.select :identity_card_id, @identities.map{ |l| [l.name, l.id, {"data-imageurl" => image_url(l.card_image), "data-deck_minimum_cards" => l.deck_minimum_cards, "data-max_influence" => l.max_influence, "data-identity_slug" => l.identity.slug}] } %>
        </div>

        <!-- List group -->
        <ul class="list-group">
          <li class="list-group-item card-image">
            <img src="" />
          </li>
          <li class="list-group-item maximum-influence">
            <span class="label label-default remaining"></span> of <span class="label label-default maximum"></span> Influence
          </li>

          <li class="list-group-item number-of-cards">
            <span class="label label-default"></span> Cards
          </li>

          <% if @deck.faction.name.downcase == "corporation" %>
            <li class="list-group-item agenda-required">
              <span class="label label-default agenda"></span> of <span class="label label-default min-agenda"></span> to <span class="label label-default max-agenda"></span> Agenda
            </li>
          <% end %>
        </ul>
      </div>

      <div class="card-list panel panel-default">
        <div class="panel-heading">Cards</div>
        <table class="table">
          <thead>
            <tr>
              <th>Number</th>
              <th>Card</th>
            </tr>
          </thead>
          <tbody>

          </tbody>
        </table>
      </div>
    </div>

    <div class="card-selection col-md-7"%>
      <% count = 0 %>

      <div class="btn-toolbar card-toggles" role="toolbar">
        <div class="btn-group">
          <button type="button" class="neutral btn btn-default" title="neutral">
            <i class="icon icon-neutral"></i>
          </button>

          <% @identities.collect(&:identity).uniq.each do |card_type| %>
            <button type="button" class="<%= card_type.slug %> btn btn-default" title="<%= card_type.name %>">
              <i class="icon icon-<%= card_type.slug %>"></i>
            </button>
          <% end %>
        </div>

        <div class="btn-group">
          <% @cards.each do |card_type, cards| %>
            <button type="button" class="<%= card_type %> btn btn-default" title="<%= card_type.to_s.titleize %>">
              <i class="icon icon-<%= card_type %>"></i>
            </button>
          <% end %>
        </div>
      </div>

      <% @cards.each do |card_type, cards| %>
        <div class="<%= card_type.to_s%> panel panel-default">

          <div class="panel-heading"><%= card_type.to_s.titleize %> cards</div>
          <div class="table-responsive">
            <table class="table">
              <tr>
                <th>Number</th>
                <th>Name</th>
                <th>Identity</th>
                <th>Types</th>
                <th>Influence</th>
              </tr>

              <tbody>
                <% cards.each do |card| %>
                  <%= render partial: "deck_card", locals: {card: card, count: count} %>
                  <% count += 1 %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
    </div>


    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<% content_for :title, "Editing #{@deck.name}" %>
<%= render partial: "form" %>

<% content_for :js_page, raw("Deck.page = new Deck.DeckPage();") %>

app/views/decks/index.html.erb
<% content_for :title, "Your decks" %>
<div class="row">
  <%= link_to "Create a new Runner deck", decks_new_runner_path, class: "btn btn-primary" %>
  <%= link_to "Create a new Corporation deck", decks_new_corporation_path, class: "btn btn-primary" %>
</div>

<% if @decks.any? %>
  <div class="row">
    <table class="decks table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Identity</th>
        </tr>
      </thead>
      <tbody>
        <% @decks.each do |deck| %>
          <tr>
            <td class="image"><%= image_tag Card.find(deck.identity_card_id).card_image %></td>
            <td><%= link_to deck.name, deck_path(deck) %></td>
            <td><%= link_to Card.find(deck.identity_card_id).name, deck_path(deck) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/decks/new.html.erb
<% content_for :title, "New deck" %>
<%= render partial: "form" %>

<% content_for :js_page, raw("Deck.page = new Deck.DeckPage();") %>