config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :data_packs, only: [:index, :show], path: '/data-packs'
  resources :card_types, only: [:show], path: '/card-types'
  resources :cards, only: [:index, :show]
  get "/decks/new/corporation", to: 'decks#new', faction: "Corporation"
  get "/decks/new/runner", to: 'decks#new', faction: "Runner"
  get "/decks/:id", to: 'decks#edit'
  resources :decks, except: [:edit]

  root 'pages#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/data_pack.rb
class DataPack < ActiveRecord::Base
  has_many :cards
  mount_uploader :box, BoxUploader

  extend FriendlyId
  friendly_id :name, use: :slugged

  def box_image
    "data_packs/#{slug}.png"
  end
end

app/controllers/data_packs_controller.rb
class DataPacksController < ApplicationController
  def index
    @data_packs = DataPack.all.sort_by &:created_at
  end

  def show
    @data_pack = DataPack.friendly.find(params[:id])
  end
end

app/views/data_packs/index.html.erb
<%= cache ['decks#index', 'v1'], :expires_in => 1.hour do %>
  <% content_for :title, "Data Packs" %>
  <% @data_packs.each do |data_pack| %>
    <div class="pack row">
      <div class="col-xs-2">
        <%= image_tag data_pack.box_image %>
      </div>

      <div class="col-xs-10 ">
        <h2><%= link_to data_pack.name, data_pack_path(data_pack) %></h2>
      </div>
    </div>
  <% end %>
<% end %>

app/views/data_packs/show.html.erb
<%= cache ['decks#show', @data_pack, 'v1'], :expires_in => 1.hour do %>
  <% content_for :title, @data_pack.name %>
  <div class="pack row">
    <div class="col-xs-3">
      <%= image_tag @data_pack.box_image %>
    </div>

    <div class="col-xs-9 ">
      <h2><%= @data_pack.name %></h2>
    </div>
  </div>

  <div class="row">
    <% @data_pack.cards.each do |card| %>
      <div class="card col-xs-4 col-md-3">
        <%= link_to image_tag(card.card_image), card_path(card) %>
      </div>
    <% end %>
  </div>
<% end %>